"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-04-21 23:03:22.374426
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('identifiers_hash', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('reappeared_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deletion_device_id', 'deletion_events', ['device_id'], unique=False)
    op.create_index('ix_deletion_identifiers', 'deletion_events', ['identifiers_hash'], unique=False)
    op.create_table('entity_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('battery', 'connectivity', name='entity_role_enum', create_constraint=True), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'role', name='uq_entity_roles_device_role')
    )
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'policy_id', name='uq_exceptions_device_policy')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exceptions')
    op.drop_table('entity_roles')
    op.drop_index('ix_deletion_identifiers', table_name='deletion_events')
    op.drop_index('ix_deletion_device_id', table_name='deletion_events')
    op.drop_table('deletion_events')
    # ### end Alembic commands ###
