from collections.abc import Callable
from typing import Protocol, runtime_checkable

from home_curator.ha_client.models import (
    HAArea,
    HADevice,
    HADeviceUpdate,
    HAEntity,
    HAEntityUpdate,
    HAEvent,
)

EventHandler = Callable[[HAEvent], None]


@runtime_checkable
class HAClient(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def get_devices(self) -> list[HADevice]: ...
    async def get_areas(self) -> list[HAArea]: ...
    async def get_entities(self) -> list[HAEntity]: ...
    async def update_device(self, device_id: str, changes: HADeviceUpdate) -> None: ...
    async def delete_device(self, device_id: str) -> None: ...
    async def update_entity(self, entity_id: str, changes: HAEntityUpdate) -> None: ...
    async def delete_entity(self, entity_id: str) -> None: ...
    def subscribe(self, handler: EventHandler) -> Callable[[], None]: ...
