from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from home_curator.config import Settings
from home_curator.storage.models import Base
from home_curator.storage.types import TZDateTime

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Allow callers (e.g. tests) to inject a URL via set_main_option before
# env.py runs. Only fall back to Settings when no URL has been provided.
if not config.get_main_option("sqlalchemy.url"):
    settings = Settings()
    config.set_main_option("sqlalchemy.url", f"sqlite:///{settings.db_path}")

target_metadata = Base.metadata


def _render_item(type_, obj, _autogen_context):
    """Render TZDateTime columns as sa.DateTime() in autogenerated migrations.

    TZDateTime is a TypeDecorator whose wire representation is DateTime; the
    UTC tzinfo handling is application-layer only. Without this hook, Alembic
    would emit the fully-qualified class path without an import, breaking
    future migrations.
    """
    del _autogen_context
    if type_ == "type" and isinstance(obj, TZDateTime):
        return "sa.DateTime()"
    return False


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        render_as_batch=True,
        render_item=_render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            render_item=_render_item,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
