#!/usr/bin/env bash
# Register Home Curator as a locally-built add-on inside the devcontainer.
#
# Two things stop the Supervisor from building this repo's add-on directly:
#
#   1. `home-curator/config.yaml` sets `image:`, and Home Assistant treats
#      that as "pull from the registry" rather than "build from source".
#   2. The Supervisor builds an add-on using the add-on's *own directory* as
#      the Docker build context, but `home-curator/Dockerfile` does
#      `COPY apps/backend ...` — it needs the repository root.
#
# So this script does the real build itself, with the real Dockerfile and the
# correct context, then registers a thin add-on whose Dockerfile is a single
# `FROM` of the resulting image. The Supervisor gets something it can build
# trivially, and what actually runs is the production image built from your
# working tree.
#
# Re-run it after changing backend or frontend source, then rebuild the
# add-on from the Home Assistant UI.

set -euo pipefail

IMAGE_TAG="home-curator-dev:local"
ADDON_SLUG="home-curator-dev"
LOCAL_ADDONS="/mnt/supervisor/addons/local"
ADDON_DIR="${LOCAL_ADDONS}/${ADDON_SLUG}"

repo_root() {
    cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd
}

ROOT="$(repo_root)"
SOURCE_CONFIG="${ROOT}/home-curator/config.yaml"
GENERATED_TS="${ROOT}/apps/frontend/src/api/generated.ts"

if [ ! -f "$SOURCE_CONFIG" ]; then
    echo "error: ${SOURCE_CONFIG} not found — is the repo mounted correctly?" >&2
    exit 1
fi

# The frontend build stage needs this file and it is gitignored, so it has to
# be generated. It needs both uv and node, which this devcontainer image does
# not carry, so it is generated on the host instead.
if [ ! -f "$GENERATED_TS" ]; then
    cat >&2 <<'MSG'
error: apps/frontend/src/api/generated.ts is missing.

It is gitignored and generated from the backend's OpenAPI schema, and the
frontend build stage needs it. Generate it on your host (not in here — this
devcontainer has no uv/node toolchain):

    task build:frontend

then re-run this script.
MSG
    exit 1
fi

echo "==> Building ${IMAGE_TAG} from ${ROOT}"
docker build -f "${ROOT}/home-curator/Dockerfile" -t "$IMAGE_TAG" "$ROOT"

echo "==> Registering local add-on at ${ADDON_DIR}"
mkdir -p "$ADDON_DIR"

# Derived from the real config.yaml rather than duplicated, so ingress,
# mappings, permissions and version cannot drift. Only the identity changes,
# and `image:` is dropped so the Supervisor builds instead of pulling.
sed \
    -e '/^image:/d' \
    -e "s|^slug: .*|slug: ${ADDON_SLUG}|" \
    -e 's|^name: .*|name: Home Curator (dev)|' \
    "$SOURCE_CONFIG" > "${ADDON_DIR}/config.yaml"

cat > "${ADDON_DIR}/Dockerfile" <<EOF
# Generated by .devcontainer/setup-local-addon.sh — do not edit.
#
# The real image is built by that script using the repository root as build
# context, which the Supervisor cannot do on its own. This exists only to
# give the Supervisor something buildable that resolves to it.
FROM ${IMAGE_TAG}
EOF

echo
echo "Done. In Home Assistant (http://localhost:7123):"
echo "  Settings → Add-ons → Add-on Store → ⋮ → Check for updates"
echo "  Install \"Home Curator (dev)\" from Local add-ons, then Start."
echo
echo "Open it from the sidebar to exercise the real ingress path."
echo "After changing source: re-run this script, then Rebuild in the add-on UI."
